EXPERIMENT_NAME: base_bce_
SEED: 4
DATASET_DIR: ../SwinCVS/endoscapes
ANNOTATIONS_PATH: ./config/reformatted_annotations_frames.json
CHECKPOINT_DIR: ./weights
MODEL:
  ENCODER: {NAME: vit_base_patch16_dinov3.lvd1689m, IMG_SIZE: 256}
  TEMPORAL:
    NAME: gated_pooling
    GATED_POOLING: {DROPOUT: 0.2}
  CLASSIFIER: {DROPOUT: 0.5}
DATA: {DATASET_NAME: ENDOSCAPES, TEMPORAL: true, LABEL_CRITERION: null, LABEL_METHOD: hard}
TRAIN:
  EPOCHS: 15
  BATCH_SIZE: 4
  GRADIENT_ACC_BATCH_SIZE: 32
  EARLY_PATIENCE: 3
  OPTIMIZER:
    NAME: adamw
    EPS: 1.0e-08
    BETAS: [0.9, 0.999]
    WEIGHT_DECAY: 0.05
  LOSS: bce
  WARMUP_EPOCHS: 1
  FREEZE_ENCODER: true
  LR:
    TEMPORAL: {TARGET: 0.0001, END: 1.0e-05}
    CLASSIFIER: {TARGET: 0.0001, END: 1.0e-05}
DATASETS:
  ENDOSCAPES:
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    CENTER_CROP: 480
    BCE_POS_CLASS_WEIGHTS: [3.19852941, 4.46153846, 2.79518072]
    BBL_WEIGHTS:
      C1: [3.1985, 0.5926]
      C2: [4.4615, 0.5631]
      C3: [2.7952, 0.6089]
    PRIOR_ALPHA: {NU: 2, PI_C1: 0.1563, PI_C2: 0.1121, PI_C3: 0.1789}
